Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.network "public_network", use_dhcp_assigned_default_route: true

  config.vm.synced_folder "./shared/", "/shared"

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt update
    sudo apt upgrade -y
    sudo apt install -y nginx lynx vim git wget unzip dh-make devscripts

    # Get IP address
    IPADDR=$(ip -4 a | grep inet | awk '{print $2}' | cut -d "/" -f 1 | grep -E "10\\.1\\.|192\\.168\\.")
    echo "Your IP is $IPADDR"

    # Copy website files
    sudo cp -r /shared/nasa/ /var/www/

    # Create nginx config
    sudo tee /etc/nginx/sites-available/nasa > /dev/null <<EOF
server {
    listen 80;
    listen [::]:80;

    root /var/www/nasa;
    index index.html index.htm index.nginx-debian.html;

    server_name $IPADDR www.$IPADDR;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

    # Set permissions
    sudo chown -R $USER:$USER /var/www/nasa
    sudo chmod -R 755 /var/www/

    # Enable nginx site
    sudo ln -sf /etc/nginx/sites-available/nasa /etc/nginx/sites-enabled/
    sudo systemctl restart nginx

    # Clone GitHub repo (personal project) for making deb pkg
    #git clone https://github.com/stuffbymax/Bash-Theft-Auto.git
  SHELL
end
