# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "public_network",
    use_dhcp_assigned_default_route: true
  config.vm.synced_folder "./shared/", "/shared"
  config.vm.provision "shell",privileged: false, inline: <<-SHELL
  sudo apt update
  sudo apt upgrade
  sudo apt install -y nginx lynx vim git
  SHELL
end
